#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Nucleus Telemetry Brief — Daily Value Extraction
#
# Architecture docs:
#   - WINDSURF_SUPER_PROMPT.md (Phase C1)
#
# Usage:
#   npm run telemetry:brief
#
# Produces a markdown summary of:
#   - Span counts and trends
#   - Error types detected
#   - Service breakdown
#   - Actionable insights
# ──────────────────────────────────────────────────────────────

set -euo pipefail

CONTAINER_NAME="nucleus-otel-collector"
LINES=2000
BRIEF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/telemetry-notes"

# Ensure notes directory exists
mkdir -p "$BRIEF_DIR"

TIMESTAMP=$(date +%Y-%m-%d_%H%M%S)
BRIEF_FILE="$BRIEF_DIR/brief_${TIMESTAMP}.md"

# ── Pre-flight ──
if ! docker ps --format '{{.Names}}' 2>/dev/null | grep -q "^${CONTAINER_NAME}$"; then
  echo "[brief] ❌ Collector not running. Start with: npm run telemetry:up" >&2
  exit 1
fi

echo "[brief] Generating telemetry brief from last ${LINES} log lines..." >&2

LOG_OUTPUT=$(docker logs "${CONTAINER_NAME}" --tail "${LINES}" 2>&1 || true)

# ── Metrics ──
TOTAL_SPANS=$(printf "%s" "$LOG_OUTPUT" | grep -ciE "Trace ID|traceID" || true)
NUCLEUS_SPANS=$(printf "%s" "$LOG_OUTPUT" | grep -ciE "service\.name.*nucleus" || true)
ERROR_SPANS=$(printf "%s" "$LOG_OUTPUT" | grep -ciE "status.*error|StatusCode.*Error|error.*true" || true)

# Service breakdown
SERVICE_COUNTS=$(printf "%s" "$LOG_OUTPUT" | \
  grep -oE "service\.name: Str\([^)]*\)" | \
  sed -E 's/service\.name: Str\(([^)]*)\)/\1/' | \
  sort | uniq -c | sort -rn | head -10 || true)

# Error types
ERROR_TYPES=$(printf "%s" "$LOG_OUTPUT" | \
  grep -oiE "(ValueError|TypeError|KeyError|RuntimeError|ConnectionError|TimeoutError|ImportError|AttributeError|FileNotFoundError)" | \
  sort | uniq -c | sort -rn | head -10 || true)

# ── Generate Brief ──
cat > "$BRIEF_FILE" <<BRIEF
# Telemetry Brief — $(date '+%Y-%m-%d %H:%M')

## Summary

| Metric | Value |
|--------|-------|
| Log lines inspected | ${LINES} |
| Total spans | ${TOTAL_SPANS} |
| Nucleus spans | ${NUCLEUS_SPANS} |
| Error spans | ${ERROR_SPANS} |
| Error rate | $([ "$TOTAL_SPANS" -gt 0 ] && echo "scale=1; $ERROR_SPANS * 100 / $TOTAL_SPANS" | bc 2>/dev/null || echo "0")% |

## Services (Top 10)

\`\`\`
${SERVICE_COUNTS:-No service data available}
\`\`\`

## Error Types Detected

\`\`\`
${ERROR_TYPES:-No errors detected}
\`\`\`

## Insights

$(if [ "$TOTAL_SPANS" = "0" ]; then
  echo "- ⚠️ **No spans detected.** Pipeline may not be flowing. Check collector + drain."
elif [ "$ERROR_SPANS" -gt 0 ]; then
  echo "- 🔴 **${ERROR_SPANS} error spans detected.** Review error types above."
  echo "- Run \`nucleus combo diagnose \"telemetry errors\"\` for automated diagnosis."
else
  echo "- ✅ **Pipeline healthy.** ${TOTAL_SPANS} spans flowing with zero errors."
fi)

## Actions

- Review: \`docker logs nucleus-otel-collector --tail 50\`
- Summary: \`npm run telemetry:summary\`
- Full audit: \`npm run telemetry:audit\`

---
*Generated by telemetry-brief.sh at $(date -u '+%Y-%m-%dT%H:%M:%SZ')*
BRIEF

echo "[brief] ✅ Brief written to: $BRIEF_FILE" >&2

# Also print to stdout for LLM consumption
cat "$BRIEF_FILE"
