// Eidetic — Notion Sync Worker
//
// Bridges a Notion database (one per user) into the user's own eideticd daemon
// via Cloudflare tunnel. Each Notion page becomes one engram (surface=notion).
// The Worker is a thin relay; no Notion page content is stored on Cloudflare.
// Only the per-database last-edited-time checkpoint persists in KV so polling
// is idempotent.
//
// Notion offers two delivery paths for changes:
//
//   (a) Webhooks   — currently in beta; trigger surface is narrow ("page
//                    property changed" / "page added" etc.) and requires
//                    integration approval for production volumes. We accept
//                    webhooks when configured, but...
//   (b) Polling    — the documented, GA, no-magic path. /notion/poll is the
//                    primary mechanism: it asks the Notion API for every page
//                    in the DB whose `last_edited_time > checkpoint` and POSTs
//                    each as an engram.
//
// We support BOTH so an operator can flip from polling to webhooks once the
// webhook beta stabilises without re-installing the integration.
//
// Routes:
//   GET  /healthz             — Worker liveness probe.
//   GET  /notion/setup        — HTML form: paste Notion token + DB ID +
//                               bridge URL + bridge token + admin secret.
//   POST /notion/setup        — Form submit handler; verifies Notion token
//                               via /v1/users/me, then writes config to KV.
//   POST /notion/webhook      — Notion webhook receiver. Verifies
//                               `X-Notion-Signature` against NOTION_WEBHOOK_SECRET
//                               (constant-time HMAC-SHA256), then fetches the
//                               changed page and POSTs to user's daemon.
//   GET  /notion/poll         — Manual / cron-friendly trigger. Reads all rows
//                               from the configured DB where last_edited_time
//                               > checkpoint, POSTs each as engram, advances
//                               the checkpoint atomically on success.
//
// Secrets (wrangler secret put):
//   ADMIN_SECRET              — Required header / form field for both
//                               /notion/setup (POST) and /notion/poll. Without
//                               it any internet caller could trigger a poll
//                               against the user's daemon or overwrite their
//                               config. Generated by the operator once via
//                               `openssl rand -hex 32`.
//   NOTION_WEBHOOK_SECRET     — (optional) Notion's webhook signing secret.
//                               Only required if /notion/webhook is wired up
//                               to a Notion integration's webhook config.
//
// KV bindings:
//   EIDETIC_NOTION_KV         — namespace storing:
//                                 user:<admin_secret_hash> →
//                                   JSON {notion_token, db_id, bridge_url,
//                                         bridge_token, configured_at}
//                                 notion:db:<db_id>:last_edited →
//                                   ISO 8601 timestamp string
//
// Trust boundary (per ADR-020, mirroring slack-app / discord-bot / telegram-bot):
//   - Notion integration token + bridge URL + bridge bearer token ARE
//     customer-provided sensitive data. Stored in Workers KV (encryption-at-
//     rest = Cloudflare-managed key, not customer-managed).
//   - Notion PAGE CONTENT is NEVER stored on Cloudflare. We read it in-memory
//     during a poll/webhook turn, POST it to the user's bridge, then drop it.
//     Only the checkpoint timestamp persists (and that's just an ISO string).
//   - DB ID is treated as a routing key, not a secret — it can appear in
//     Cloudflare request logs. README §Privacy documents this.

const NOTION_API_BASE   = "https://api.notion.com/v1";
const NOTION_API_VERSION = "2022-06-28";
const BRIDGE_FETCH_TIMEOUT_MS = 12_000;
const NOTION_FETCH_TIMEOUT_MS = 15_000;
const POLL_PAGE_SIZE = 100;          // Notion API max per page is 100.
const POLL_MAX_PAGES = 20;           // Safety cap: 20*100 = 2000 rows per turn.
const BLOCK_PAGE_SIZE = 100;
const BLOCK_MAX_PAGES = 10;          // Per-page block fetch cap.
const ENGRAM_BODY_MAX_CHARS = 32_000; // Per-page body cap to keep bridge POST sane.

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      return json({ ok: true, service: "eidetic-notion" });
    }

    if (url.pathname === "/notion/setup") {
      if (request.method === "GET")  return renderSetupPage(url);
      if (request.method === "POST") return handleSetupSubmit(request, env);
      return new Response("method not allowed", { status: 405 });
    }

    if (url.pathname === "/notion/webhook") {
      if (request.method !== "POST") return new Response("method not allowed", { status: 405 });
      return handleWebhook(request, env, ctx);
    }

    if (url.pathname === "/notion/poll") {
      if (request.method !== "GET") return new Response("method not allowed", { status: 405 });
      return handlePoll(request, env, ctx);
    }

    return new Response("not found", { status: 404 });
  },
};

// ---------------------------------------------------------------------------
// /notion/webhook — HMAC-verified Notion webhook handler
// ---------------------------------------------------------------------------
//
// Notion's beta webhooks include an `X-Notion-Signature` header containing
// `sha256=<hex>` where `<hex>` is HMAC-SHA256 of the raw request body keyed
// by the integration's webhook signing secret. We verify constant-time, then
// pull the referenced page via the Notion API (the webhook payload only
// gives us the page_id; we still need a full fetch to render the body).

async function handleWebhook(request, env, ctx) {
  const rawBody = await request.text();

  if (!env.NOTION_WEBHOOK_SECRET) {
    console.warn("notion: webhook hit but NOTION_WEBHOOK_SECRET unset");
    return new Response("webhook not configured", { status: 503 });
  }

  const sig = request.headers.get("x-notion-signature") || "";
  const verified = await verifyNotionSignature({
    signingSecret: env.NOTION_WEBHOOK_SECRET,
    signature: sig,
    rawBody,
  });
  if (!verified) {
    console.warn("notion: bad webhook signature");
    return new Response("invalid signature", { status: 401 });
  }

  let event;
  try {
    event = JSON.parse(rawBody);
  } catch {
    return new Response("invalid JSON", { status: 400 });
  }

  // Notion's beta webhook handshake: when you first register the URL, Notion
  // POSTs `{ "verification_token": "..." }` and expects us to echo it back.
  if (event && typeof event.verification_token === "string") {
    return json({ verification_token: event.verification_token });
  }

  const pageId = extractPageIdFromEvent(event);
  if (!pageId) {
    // Unknown event shape — ack so Notion doesn't redeliver, log for debug.
    console.warn("notion: webhook event had no page_id we could route");
    return new Response("ok", { status: 200 });
  }

  // We need a configured user to know which bridge to POST at. Webhooks don't
  // carry the admin secret, so we look up the route by DB ID embedded in the
  // event (Notion includes parent.database_id for page events).
  const dbId = extractDbIdFromEvent(event);
  if (!dbId) {
    console.warn("notion: webhook event had no parent db_id");
    return new Response("ok", { status: 200 });
  }

  const config = await loadConfigByDbId(env, dbId);
  if (!config) {
    console.warn(`notion: webhook for db ${dbId} but no user configured`);
    return new Response("ok", { status: 200 });
  }

  ctx.waitUntil(syncSinglePage({ env, config, pageId }));
  return new Response("ok", { status: 200 });
}

function extractPageIdFromEvent(event) {
  // Several possible shapes across the webhook beta — try the documented
  // fields and fall back to the entity-style payload.
  return (
    event?.page?.id ||
    event?.entity?.id ||
    event?.data?.page_id ||
    event?.page_id ||
    null
  );
}

function extractDbIdFromEvent(event) {
  return (
    event?.page?.parent?.database_id ||
    event?.entity?.parent?.database_id ||
    event?.data?.parent_id ||
    event?.parent?.database_id ||
    null
  );
}

// ---------------------------------------------------------------------------
// /notion/poll — checkpoint-driven sync of the full configured DB
// ---------------------------------------------------------------------------
//
// Cron-friendly: `*/15 * * * * curl -H "X-Admin-Secret: …" \
//   https://notion.eidetic.works/notion/poll`
//
// Loads the per-user config (looked up via ADMIN_SECRET → only the matching
// user can poll their own DB), queries the Notion DB for pages where
// last_edited_time > checkpoint, POSTs each as an engram, and only advances
// the checkpoint after the whole batch succeeds. Failures leave the
// checkpoint untouched so the next poll retries the same window.

async function handlePoll(request, env, ctx) {
  const adminSecret =
    request.headers.get("x-admin-secret") ||
    new URL(request.url).searchParams.get("admin_secret") ||
    "";
  if (!env.ADMIN_SECRET || !constantTimeEqual(adminSecret, env.ADMIN_SECRET)) {
    return new Response("forbidden", { status: 403 });
  }

  const config = await loadConfigByAdminSecret(env);
  if (!config) {
    return json({ ok: false, error: "no user configured; visit /notion/setup first" }, 412);
  }

  const checkpointKey = `notion:db:${config.db_id}:last_edited`;
  const checkpoint = (await env.EIDETIC_NOTION_KV.get(checkpointKey)) || "";

  let pages;
  try {
    pages = await queryDbSinceCheckpoint({
      notionToken: config.notion_token,
      dbId: config.db_id,
      checkpoint,
    });
  } catch (err) {
    return json({ ok: false, error: `notion query failed: ${err.message || err}` }, 502);
  }

  if (pages.length === 0) {
    return json({ ok: true, scanned: 0, posted: 0, checkpoint });
  }

  let posted = 0;
  let failed = 0;
  let newestSeen = checkpoint;
  for (const page of pages) {
    try {
      await syncSinglePageWithBody({
        env,
        config,
        page,
      });
      posted++;
      if (page.last_edited_time && page.last_edited_time > newestSeen) {
        newestSeen = page.last_edited_time;
      }
    } catch (err) {
      failed++;
      console.warn(
        `notion: page ${page.id} failed: ${String(err.message || err).slice(0, 240)}`,
      );
    }
  }

  // Advance the checkpoint only if at least one page succeeded AND newestSeen
  // actually moved. This way a transient all-fail keeps the window so the next
  // cron tick retries.
  if (posted > 0 && newestSeen && newestSeen > checkpoint) {
    await env.EIDETIC_NOTION_KV.put(checkpointKey, newestSeen);
  }

  return json({
    ok: true,
    scanned: pages.length,
    posted,
    failed,
    checkpoint_before: checkpoint || null,
    checkpoint_after: newestSeen || checkpoint || null,
  });
}

async function queryDbSinceCheckpoint({ notionToken, dbId, checkpoint }) {
  // Notion's databases.query supports a `filter` on `last_edited_time`. When
  // we have no checkpoint we ask for the full DB (sorted oldest-first so the
  // newest timestamp falls out at the end of the batch).
  const out = [];
  let cursor = undefined;
  for (let pageIdx = 0; pageIdx < POLL_MAX_PAGES; pageIdx++) {
    const body = {
      page_size: POLL_PAGE_SIZE,
      sorts: [{ timestamp: "last_edited_time", direction: "ascending" }],
    };
    if (cursor) body.start_cursor = cursor;
    if (checkpoint) {
      body.filter = {
        timestamp: "last_edited_time",
        last_edited_time: { after: checkpoint },
      };
    }

    const res = await notionFetch(
      `${NOTION_API_BASE}/databases/${encodeURIComponent(dbId)}/query`,
      {
        method: "POST",
        notionToken,
        body: JSON.stringify(body),
      },
    );
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      throw new Error(`databases.query HTTP ${res.status}: ${detail.slice(0, 240)}`);
    }
    const data = await res.json();
    for (const r of data.results || []) out.push(r);
    if (!data.has_more || !data.next_cursor) break;
    cursor = data.next_cursor;
  }
  return out;
}

// ---------------------------------------------------------------------------
// Per-page sync — both webhook (fetch first) and poll (already have summary)
// ---------------------------------------------------------------------------

async function syncSinglePage({ env, config, pageId }) {
  // Webhook path: we have only the ID, fetch the page summary then full body.
  let page;
  try {
    const res = await notionFetch(`${NOTION_API_BASE}/pages/${encodeURIComponent(pageId)}`, {
      method: "GET",
      notionToken: config.notion_token,
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      console.warn(`notion: fetch page ${pageId} HTTP ${res.status}: ${detail.slice(0, 240)}`);
      return;
    }
    page = await res.json();
  } catch (err) {
    console.warn(`notion: fetch page ${pageId} threw: ${String(err.message || err).slice(0, 240)}`);
    return;
  }
  try {
    await syncSinglePageWithBody({ env, config, page });
  } catch (err) {
    console.warn(`notion: sync page ${pageId} failed: ${String(err.message || err).slice(0, 240)}`);
  }
}

async function syncSinglePageWithBody({ env, config, page }) {
  const title = extractPageTitle(page);
  const body = await fetchPagePlainText({
    notionToken: config.notion_token,
    pageId: page.id,
  });

  // Compose the engram. Body cap protects the daemon from a runaway Notion
  // page (some users keep multi-thousand-block docs). We truncate and tag.
  let payload = body;
  let truncated = false;
  if (payload.length > ENGRAM_BODY_MAX_CHARS) {
    payload = payload.slice(0, ENGRAM_BODY_MAX_CHARS);
    truncated = true;
  }
  const engram = {
    surface: "notion",
    title,
    payload,
    meta: {
      notion_page_id: page.id,
      notion_db_id: config.db_id,
      notion_url: page.url || "",
      last_edited_time: page.last_edited_time || "",
      truncated,
    },
  };

  await postEngram({
    bridgeUrl: config.bridge_url,
    bridgeToken: config.bridge_token,
    engram,
  });
}

async function postEngram({ bridgeUrl, bridgeToken, engram }) {
  const url = `${bridgeUrl.replace(/\/+$/, "")}/engrams`;
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), BRIDGE_FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${bridgeToken}`,
      },
      body: JSON.stringify(engram),
      signal: controller.signal,
    });
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      throw new Error(`bridge POST /engrams HTTP ${res.status}: ${detail.slice(0, 240)}`);
    }
  } finally {
    clearTimeout(t);
  }
}

// ---------------------------------------------------------------------------
// Notion page → plain text
// ---------------------------------------------------------------------------
//
// Notion's content model is a tree of blocks (paragraph, heading_*, bulleted,
// numbered, toggle, quote, code, callout, to_do, …). We flatten to plain
// text: one block per line, dropping the hierarchy. This matches the engram
// model — daemons index full-text, not structured layout.
//
// We only walk top-level blocks; nested blocks (toggle children, list children)
// are fetched up to BLOCK_MAX_PAGES levels deep via has_children=true checks.
// In practice most rows are short enough that we cap at the top level only.

async function fetchPagePlainText({ notionToken, pageId }) {
  const blocks = await fetchAllBlockChildren({ notionToken, blockId: pageId });
  const out = [];
  for (const b of blocks) {
    const line = blockToPlainText(b);
    if (line) out.push(line);
  }
  return out.join("\n");
}

async function fetchAllBlockChildren({ notionToken, blockId }) {
  const out = [];
  let cursor = undefined;
  for (let pageIdx = 0; pageIdx < BLOCK_MAX_PAGES; pageIdx++) {
    const u = new URL(`${NOTION_API_BASE}/blocks/${encodeURIComponent(blockId)}/children`);
    u.searchParams.set("page_size", String(BLOCK_PAGE_SIZE));
    if (cursor) u.searchParams.set("start_cursor", cursor);
    const res = await notionFetch(u.toString(), { method: "GET", notionToken });
    if (!res.ok) {
      // Don't fail the whole engram for a partial block fetch; log + return
      // what we have.
      console.warn(`notion: block children HTTP ${res.status} on ${blockId}`);
      break;
    }
    const data = await res.json();
    for (const r of data.results || []) out.push(r);
    if (!data.has_more || !data.next_cursor) break;
    cursor = data.next_cursor;
  }
  return out;
}

function blockToPlainText(block) {
  const type = block?.type;
  if (!type) return "";
  const node = block[type];
  if (!node) return "";

  // Most block types carry a rich_text array we can concatenate.
  const rt = Array.isArray(node.rich_text) ? node.rich_text : null;
  const text = rt ? rt.map((r) => r.plain_text || "").join("") : "";

  switch (type) {
    case "paragraph":
    case "quote":
    case "callout":
      return text;
    case "heading_1": return text ? `# ${text}` : "";
    case "heading_2": return text ? `## ${text}` : "";
    case "heading_3": return text ? `### ${text}` : "";
    case "bulleted_list_item": return text ? `- ${text}` : "";
    case "numbered_list_item": return text ? `1. ${text}` : "";
    case "to_do": {
      const checked = node.checked ? "x" : " ";
      return text ? `- [${checked}] ${text}` : "";
    }
    case "toggle": return text;
    case "code": {
      const lang = node.language || "";
      return text ? "```" + lang + "\n" + text + "\n```" : "";
    }
    case "divider": return "---";
    case "bookmark":
    case "embed":
    case "link_preview":
      return node.url || "";
    default:
      // Unknown / unsupported (e.g. child_page, child_database, image, file,
      // video, …). Skip silently — they don't contribute to text search.
      return "";
  }
}

function extractPageTitle(page) {
  // Title lives in whichever property has type === "title" (databases) or in
  // page.properties.title for non-DB pages.
  const props = page?.properties || {};
  for (const key of Object.keys(props)) {
    const p = props[key];
    if (p?.type === "title" && Array.isArray(p.title)) {
      const t = p.title.map((r) => r.plain_text || "").join("").trim();
      if (t) return t;
    }
  }
  return "(untitled)";
}

// ---------------------------------------------------------------------------
// Notion fetch wrapper — timeouts + required headers
// ---------------------------------------------------------------------------

async function notionFetch(url, { method = "GET", notionToken, body = undefined }) {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), NOTION_FETCH_TIMEOUT_MS);
  try {
    return await fetch(url, {
      method,
      headers: {
        Authorization: `Bearer ${notionToken}`,
        "Notion-Version": NOTION_API_VERSION,
        "Content-Type": "application/json",
      },
      body,
      signal: controller.signal,
    });
  } finally {
    clearTimeout(t);
  }
}

// ---------------------------------------------------------------------------
// HMAC-SHA256 verification for Notion webhook signatures
// ---------------------------------------------------------------------------
//
// Notion's webhook signature header is "sha256=<hex>" — the same shape as
// GitHub's HMAC. We import the secret, verify the hex against the raw body.

async function verifyNotionSignature({ signingSecret, signature, rawBody }) {
  if (!signingSecret || !signature) return false;
  if (!signature.startsWith("sha256=")) return false;
  const sigHex = signature.slice("sha256=".length);
  const sigBytes = hexToBytes(sigHex);
  if (!sigBytes) return false;

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(signingSecret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["verify"],
  );
  return crypto.subtle.verify("HMAC", key, sigBytes, new TextEncoder().encode(rawBody));
}

function hexToBytes(hex) {
  if (hex.length % 2 !== 0) return null;
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) return null;
    out[i] = byte;
  }
  return out;
}

// ---------------------------------------------------------------------------
// /notion/setup — HTML form for the operator (one user per Worker)
// ---------------------------------------------------------------------------
//
// Unlike the multi-tenant Slack / Discord / Telegram workers, the Notion
// integration is intentionally single-tenant per Worker deploy: a Notion
// internal integration token is workspace-scoped, and one operator typically
// runs one DB → daemon pipeline. The admin secret gates both setup and poll.

function renderSetupPage(url) {
  const prefilledDb = url.searchParams.get("db_id") || "";
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Eidetic for Notion — Setup</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font: 16px/1.5 system-ui, sans-serif; max-width: 600px; margin: 4rem auto; padding: 0 1rem; color: #222; }
  h1 { font-size: 1.4rem; margin: 0 0 .5rem; }
  p  { color: #555; }
  label { display: block; margin: 1rem 0 .25rem; font-weight: 600; }
  input[type=text], input[type=password] { width: 100%; padding: .55rem .65rem; border: 1px solid #ccc; border-radius: 6px; font: inherit; }
  button { margin-top: 1.25rem; padding: .65rem 1.1rem; border: 0; border-radius: 6px; background: #000; color: #fff; font: inherit; cursor: pointer; }
  small { color: #777; }
  code { background: #f1f1f4; padding: .1rem .3rem; border-radius: 4px; }
</style>
</head>
<body>
  <h1>Connect a Notion database to your eidetic-daemon</h1>
  <p>One-time setup. You'll need:</p>
  <ul>
    <li>An internal integration token from
        <a href="https://www.notion.so/my-integrations">notion.so/my-integrations</a>
        (start with "secret_").</li>
    <li>The database ID — the 32-character hex blob in your DB URL.</li>
    <li>The bridge URL + token of your local <code>eideticd -bridge</code>.</li>
    <li>The Worker's <code>ADMIN_SECRET</code> (set via <code>wrangler secret put</code>).</li>
  </ul>
  <p><small>The DB must be <em>shared with the integration</em> (open it in
     Notion → "..." menu → Add connections → pick your integration). Otherwise
     Notion returns 404 on the query.</small></p>
  <form method="POST" action="/notion/setup">
    <label for="admin_secret">Admin secret</label>
    <input id="admin_secret" name="admin_secret" type="password" required>
    <small>Same value you set with <code>wrangler secret put ADMIN_SECRET</code>.</small>
    <label for="notion_token">Notion integration token</label>
    <input id="notion_token" name="notion_token" type="password" required
           placeholder="secret_…">
    <small>Verified via <code>GET /v1/users/me</code> before save.</small>
    <label for="db_id">Notion database ID</label>
    <input id="db_id" name="db_id" type="text" required
           value="${escapeHtml(prefilledDb)}"
           placeholder="32-character hex">
    <small>From the DB URL: <code>notion.so/<em>workspace</em>/<strong>32hex</strong>?v=…</code>.</small>
    <label for="bridge_url">Bridge URL</label>
    <input id="bridge_url" name="bridge_url" type="text" required
           placeholder="https://something.trycloudflare.com">
    <small>Must be HTTPS on <code>*.trycloudflare.com</code> or <code>*.cloudflare.com</code>.</small>
    <label for="bridge_token">Bridge bearer token</label>
    <input id="bridge_token" name="bridge_token" type="password" required>
    <small>Contents of <code>~/.eidetic/bridge-token</code> on the daemon host.</small>
    <button type="submit">Save</button>
  </form>
</body>
</html>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

async function handleSetupSubmit(request, env) {
  const rawBody = await request.text();
  const form = parseFormUrlEncoded(rawBody);
  const adminSecret  = (form.admin_secret  || "").trim();
  const notionToken  = (form.notion_token  || "").trim();
  const dbId         = (form.db_id         || "").trim().replace(/-/g, "");
  const bridgeUrl    = (form.bridge_url    || "").trim();
  const bridgeToken  = (form.bridge_token  || "").trim();

  if (!env.ADMIN_SECRET || !constantTimeEqual(adminSecret, env.ADMIN_SECRET)) {
    return new Response("Invalid admin secret.", { status: 403 });
  }
  if (!/^[A-Za-z0-9_]{20,}$/.test(notionToken)) {
    return new Response(
      "Notion token looks wrong. Expected the value from notion.so/my-integrations " +
      "(starts with 'secret_' or 'ntn_', 20+ chars).",
      { status: 400 },
    );
  }
  if (!/^[a-f0-9]{32}$/i.test(dbId)) {
    return new Response(
      "Database ID must be the 32-character hex blob from the DB URL " +
      "(dashes are stripped automatically).",
      { status: 400 },
    );
  }
  if (!isAllowedBridgeUrl(bridgeUrl)) {
    return new Response(
      "Bridge URL must be HTTPS on *.trycloudflare.com or *.cloudflare.com. " +
      "Wider hostnames are intentionally rejected so a misconfigured install " +
      "can't be redirected at an arbitrary internet endpoint.",
      { status: 400 },
    );
  }
  if (!bridgeToken || bridgeToken.length < 16) {
    return new Response(
      "Bearer token looks too short — paste the full contents of ~/.eidetic/bridge-token.",
      { status: 400 },
    );
  }

  // Verify the Notion token via /v1/users/me. Cheap call, catches typos.
  const meRes = await notionFetch(`${NOTION_API_BASE}/users/me`, {
    method: "GET",
    notionToken,
  }).catch(() => null);
  if (!meRes || !meRes.ok) {
    const status = meRes ? meRes.status : "no-response";
    return new Response(
      `Could not verify Notion token via /v1/users/me (HTTP ${status}). ` +
      `Re-check the token from notion.so/my-integrations.`,
      { status: 400 },
    );
  }

  // Verify the integration has actually been shared on the DB. Without this
  // the user discovers the failure only at first poll, which is bad UX.
  const dbRes = await notionFetch(
    `${NOTION_API_BASE}/databases/${encodeURIComponent(dbId)}`,
    { method: "GET", notionToken },
  ).catch(() => null);
  if (!dbRes || !dbRes.ok) {
    const status = dbRes ? dbRes.status : "no-response";
    return new Response(
      `Notion DB lookup failed (HTTP ${status}). Most likely the DB is not ` +
      `shared with this integration — open it in Notion, click "..." → ` +
      `Add connections, and pick your integration.`,
      { status: 400 },
    );
  }

  const cfg = {
    notion_token: notionToken,
    db_id: dbId,
    bridge_url: bridgeUrl,
    bridge_token: bridgeToken,
    configured_at: new Date().toISOString(),
  };
  await env.EIDETIC_NOTION_KV.put(userKey(), JSON.stringify(cfg));
  // Maintain a reverse index db_id → config-key so webhook routing can find
  // the user from a webhook payload that only carries the DB ID.
  await env.EIDETIC_NOTION_KV.put(dbIndexKey(dbId), userKey());

  const html = `<!doctype html><meta charset="utf-8">
<title>Saved</title>
<body style="font: 16px/1.5 system-ui, sans-serif; max-width: 560px; margin: 4rem auto; padding: 0 1rem;">
<h1>Saved.</h1>
<p>Trigger an initial sync with:</p>
<pre><code>curl -H "X-Admin-Secret: &lt;your-admin-secret&gt;" \\
     https://${escapeHtml(new URL(request.url).host)}/notion/poll</code></pre>
<p>The first call will sync every page in the DB (checkpoint is empty).
   Subsequent calls only sync pages with <code>last_edited_time</code> newer
   than the checkpoint.</p>
<p>For continuous sync add a cron entry that hits <code>/notion/poll</code>
   every 15 minutes — or wire up Notion's webhook beta to
   <code>/notion/webhook</code>.</p>
</body>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

// Bridge URL allowlist — same posture as slack-app / discord-bot / telegram-bot.
function isAllowedBridgeUrl(raw) {
  let u;
  try { u = new URL(raw); } catch { return false; }
  if (u.protocol !== "https:") return false;
  const host = u.hostname.toLowerCase();
  return host.endsWith(".trycloudflare.com") || host.endsWith(".cloudflare.com");
}

// ---------------------------------------------------------------------------
// KV helpers
// ---------------------------------------------------------------------------
//
// Single-tenant Worker → one config key. We hash nothing here because the
// ADMIN_SECRET gates writes; the key is just a fixed string.

function userKey() { return "user:default"; }
function dbIndexKey(dbId) { return `db_index:${dbId}`; }

async function loadConfigByAdminSecret(env) {
  const raw = await env.EIDETIC_NOTION_KV.get(userKey());
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

async function loadConfigByDbId(env, dbId) {
  const key = await env.EIDETIC_NOTION_KV.get(dbIndexKey(dbId));
  if (!key) return null;
  const raw = await env.EIDETIC_NOTION_KV.get(key);
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

// ---------------------------------------------------------------------------
// Constant-time string compare (same pattern as telegram-bot)
// ---------------------------------------------------------------------------

function constantTimeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length === 0 || b.length === 0) return false;
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

// ---------------------------------------------------------------------------
// Generic helpers
// ---------------------------------------------------------------------------

function parseFormUrlEncoded(body) {
  const out = {};
  for (const pair of body.split("&")) {
    if (!pair) continue;
    const eq = pair.indexOf("=");
    const k = eq === -1 ? pair : pair.slice(0, eq);
    const v = eq === -1 ? "" : pair.slice(eq + 1);
    out[decodeURIComponent(k.replace(/\+/g, " "))] =
      decodeURIComponent(v.replace(/\+/g, " "));
  }
  return out;
}

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
