server {
    listen       8080;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Proxy API requests if we wanted to serve API on same domain
    # location /api/ {
    #     proxy_pass ${API_URL};
    # }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
