// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffNfE6t17yZtaFi3yHVCOUSTuMCAkbd8',
    appId: '1:315814630048:web:53f66088547ee0900befc5',
    messagingSenderId: '315814630048',
    projectId: 'gentlequestapp',
    authDomain: 'gentlequestapp.firebaseapp.com',
    storageBucket: 'gentlequestapp.firebasestorage.app',
    // GA4 web stream for the gentlequestapp property (551876340), linked
    // 2026-08-27 when Google Analytics was enabled on the Firebase project.
    // Absent before that because no GA4 property existed at all — see
    // docs/gates/ADR-007 amendment.
    measurementId: 'G-MBBHN4PT39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPyj-8kRhFUAdLDuRT9Q6oTlNFak6KRc',
    appId: '1:315814630048:android:2e7d7a2af5602ce50befc5',
    messagingSenderId: '315814630048',
    projectId: 'gentlequestapp',
    storageBucket: 'gentlequestapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWsMteJMCa9sOGj1C0YtSCpy9evQPMrgU',
    appId: '1:315814630048:ios:7caf326e618f230e0befc5',
    messagingSenderId: '315814630048',
    projectId: 'gentlequestapp',
    storageBucket: 'gentlequestapp.firebasestorage.app',
    iosClientId: '315814630048-epd7c59mpo940fb3s1vruodnlcn8t01f.apps.googleusercontent.com',
    iosBundleId: 'com.gentlequest.app',
  );
}
