// Eidetic — Telegram Bot Worker
//
// Lets any Telegram user run `/eidetic <question>` in any chat (private, group,
// channel-admin DM) and have it answered by THEIR own eideticd daemon (exposed
// via Cloudflare tunnel). The Worker is a thin webhook-secret-verifying relay;
// no engram or message content is ever stored here. The user's bridge URL +
// bearer token live in Workers KV, keyed by Telegram user_id (see ADR-020 —
// no PII beyond Telegram numeric IDs).
//
// Routes:
//   GET  /healthz                          — Worker liveness probe.
//   POST /telegram/webhook                 — Telegram Update receiver.
//                                            Verifies `X-Telegram-Bot-Api-Secret-Token`
//                                            against env.WEBHOOK_SECRET (constant-
//                                            time compare). ALWAYS returns 200,
//                                            even on bad input — see § "Why 200
//                                            on everything".
//   GET  /telegram-setup                   — HTML form: paste bot token + bridge
//                                            URL + bridge token + telegram user_id.
//   POST /telegram-setup                   — Form submit handler; verifies bot
//                                            token via getMe, then writes config
//                                            to KV.
//   GET  /telegram-setup/install/<token>   — One-time webhook installer. Calls
//                                            Telegram's setWebhook with this
//                                            Worker's /telegram/webhook URL +
//                                            WEBHOOK_SECRET.
//
// Secrets (wrangler secret put):
//   WEBHOOK_SECRET     — Random 32-byte hex string. Generated by the operator
//                        once via `openssl rand -hex 32`. Telegram echoes it
//                        back in every webhook POST via the
//                        `X-Telegram-Bot-Api-Secret-Token` header (we set it
//                        when calling setWebhook). The Worker rejects any
//                        webhook whose header does not match this secret.
//   ADMIN_BOT_TOKEN    — (optional) Telegram bot token used ONLY by the
//                        /telegram-setup/install path when the user hasn't
//                        passed a token in the URL. Most installs use the
//                        path-param form; this is a convenience for operators
//                        running a single bot.
//
// KV bindings:
//   EIDETIC_TELEGRAM_KV  — namespace storing user:<telegram_user_id>
//                          values: JSON {bridge_url, token, configured_at}
//
// Trust boundary (per ADR-020, mirroring slack-app + discord-bot):
//   - Bridge URL + bearer token ARE customer-provided sensitive data.
//   - Stored in Workers KV (encryption-at-rest = Cloudflare-managed key).
//   - Only Telegram user_id is retained as key. Chat_id is captured at
//     ask-time to address the reply, but is NEVER persisted.
//   - Token is read only on the synchronous /telegram/webhook path and
//     forwarded to the user's own bridge URL over HTTPS. Never logged.
//   - Message text is NEVER persisted (only held in memory for the duration
//     of the request, to build the reply).
//
// ---------------------------------------------------------------------------
// Webhook secret verification approach
// ---------------------------------------------------------------------------
// Telegram's webhook auth model differs sharply from Slack's HMAC and
// Discord's Ed25519. When you call `setWebhook` you pass a `secret_token`
// parameter — Telegram echoes that exact string back in the
// `X-Telegram-Bot-Api-Secret-Token` header on every webhook POST. There is
// no payload signature; verification is a single equality check against a
// shared secret.
//
// We do a **constant-time** byte-by-byte compare so a timing attacker can't
// learn the secret one character at a time. The naive `===` comparison
// short-circuits on the first mismatching byte, which on a fast-enough
// network can leak the prefix.
//
// ---------------------------------------------------------------------------
// Why 200 on everything
// ---------------------------------------------------------------------------
// Telegram's webhook delivery retries aggressively (and indefinitely with
// exponential backoff) on any non-2xx response. A misbehaving Worker that
// returns 4xx/5xx on a malformed update will get the same update redelivered
// for hours. We therefore:
//   1. Always return 200 from /telegram/webhook, even on bad secret / bad
//      JSON / unsupported update type.
//   2. Log the rejection cause to console.warn (visible in `wrangler tail`)
//      so the operator can debug without DOS-ing the Worker.
//
// The single exception is the setup/install routes, which Telegram does NOT
// retry — those return real HTTP statuses for browser-friendly errors.

const BRIDGE_FETCH_TIMEOUT_MS = 12_000;
const TOP_ENGRAMS = 3;
const ENGRAM_SNIPPET_CHARS = 240;
const COMMAND_NAME = "eidetic";
const SETUP_URL_PUBLIC = "https://eidetic.works/telegram-setup";
const TELEGRAM_API_BASE = "https://api.telegram.org";

// ---------------------------------------------------------------------------
// Router
// ---------------------------------------------------------------------------

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname === "/healthz") {
      return json({ ok: true, service: "eidetic-telegram" });
    }

    if (url.pathname === "/telegram/webhook") {
      if (request.method !== "POST") {
        // GET-ing the webhook is harmless; reply with a hint but still 200
        // so any accidental browser visit doesn't trip Telegram-style retry
        // anywhere in the stack.
        return new Response("telegram webhook endpoint (POST only)", { status: 405 });
      }
      return handleWebhook(request, env, ctx);
    }

    if (url.pathname === "/telegram-setup") {
      if (request.method === "GET")  return renderSetupPage(url);
      if (request.method === "POST") return handleSetupSubmit(request, env);
      return new Response("method not allowed", { status: 405 });
    }

    // /telegram-setup/install/<bot_token> — one-shot webhook installer.
    if (url.pathname.startsWith("/telegram-setup/install/")) {
      if (request.method !== "GET") {
        return new Response("method not allowed", { status: 405 });
      }
      const botToken = url.pathname.slice("/telegram-setup/install/".length);
      return handleInstallWebhook(botToken, request, env);
    }

    return new Response("not found", { status: 404 });
  },
};

// ---------------------------------------------------------------------------
// /telegram/webhook — secret-token-verified update handler
// ---------------------------------------------------------------------------

async function handleWebhook(request, env, ctx) {
  // 1. Verify the secret-token header before reading the body. If this fails
  //    we MUST still return 200 — see "Why 200 on everything" above — so
  //    Telegram doesn't redeliver. We log the rejection for operator debug.
  const headerSecret = request.headers.get("x-telegram-bot-api-secret-token") || "";
  if (!env.WEBHOOK_SECRET || !constantTimeEqual(headerSecret, env.WEBHOOK_SECRET)) {
    console.warn("telegram: bad webhook secret token (returning 200 to suppress retries)");
    return new Response("ok", { status: 200 });
  }

  let update;
  try {
    update = await request.json();
  } catch {
    console.warn("telegram: invalid JSON in webhook body");
    return new Response("ok", { status: 200 });
  }

  // We handle ONLY message.text starting with `/eidetic`. Everything else
  // (edited_message, channel_post, callback_query, my_chat_member, …) is
  // intentionally ignored — return 200 silently so Telegram stops retrying.
  const msg = update.message;
  const text = msg?.text || "";
  if (!msg || typeof text !== "string") {
    return new Response("ok", { status: 200 });
  }

  // Match `/eidetic` or `/eidetic@BotName` at the start (Telegram appends
  // the bot username in group chats).
  const cmdMatch = text.match(/^\/eidetic(?:@\w+)?(?:\s+(.*))?$/s);
  if (!cmdMatch) {
    return new Response("ok", { status: 200 });
  }

  const question = (cmdMatch[1] || "").trim();
  const userId = String(msg.from?.id || "");
  const chatId = msg.chat?.id;
  const messageId = msg.message_id;

  // Telegram's bot token is the same secret we use to call sendMessage. The
  // user picks WHICH bot via the setup flow — their KV entry includes the
  // bot token they configured. We pull it from KV alongside bridge_url+token.
  if (!userId || chatId == null) {
    console.warn("telegram: missing user_id / chat_id");
    return new Response("ok", { status: 200 });
  }

  // We respond asynchronously via Telegram's sendMessage API. The webhook
  // response body is unused (we already 200'd). ctx.waitUntil keeps the
  // Worker alive while we hit the bridge + Telegram.
  ctx.waitUntil(answerAndReply({ env, userId, chatId, messageId, question }));

  return new Response("ok", { status: 200 });
}

async function answerAndReply({ env, userId, chatId, messageId, question }) {
  const config = await loadUserConfig(env, userId);
  if (!config) {
    await telegramReply({
      botToken: env.ADMIN_BOT_TOKEN || "",
      chatId,
      replyToMessageId: messageId,
      text:
        `Configure your bridge URL at ${escapeMdV2(SETUP_URL_PUBLIC)} ` +
        `\\(one\\-time; use your Telegram user ID: \`${escapeMdV2(userId)}\`\\)\\.`,
    });
    return;
  }

  if (!question) {
    await telegramReply({
      botToken: config.bot_token,
      chatId,
      replyToMessageId: messageId,
      text: "Usage: `/eidetic <your question>`",
    });
    return;
  }

  try {
    const data = await askBridge(config.bridge_url, config.token, question);
    await telegramReply({
      botToken: config.bot_token,
      chatId,
      replyToMessageId: messageId,
      text: renderAnswerMarkdown(question, data),
    });
  } catch (err) {
    await telegramReply({
      botToken: config.bot_token,
      chatId,
      replyToMessageId: messageId,
      text: `Bridge call failed: ${escapeMdV2(truncate(String(err.message || err), 200))}`,
    });
  }
}

async function askBridge(bridgeUrl, token, question) {
  const url = `${bridgeUrl.replace(/\/+$/, "")}/ask?question=${encodeURIComponent(question)}`;
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), BRIDGE_FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      headers: { Authorization: `Bearer ${token}` },
      signal: controller.signal,
    });
    if (!res.ok) {
      throw new Error(`bridge HTTP ${res.status}`);
    }
    return await res.json();
  } finally {
    clearTimeout(t);
  }
}

async function telegramReply({ botToken, chatId, replyToMessageId, text }) {
  if (!botToken) {
    console.warn("telegram: cannot send reply — no bot token (user not configured?)");
    return;
  }
  const url = `${TELEGRAM_API_BASE}/bot${botToken}/sendMessage`;
  const body = {
    chat_id: chatId,
    text: truncate(text, 4000), // Telegram cap is 4096; leave margin for safety.
    parse_mode: "MarkdownV2",
    reply_parameters: { message_id: replyToMessageId },
    disable_web_page_preview: true,
  };
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!res.ok) {
      const errBody = await res.text().catch(() => "");
      console.warn(`telegram: sendMessage HTTP ${res.status}: ${errBody.slice(0, 300)}`);
    }
  } catch (err) {
    console.warn(`telegram: sendMessage threw: ${String(err.message || err).slice(0, 300)}`);
  }
}

// ---------------------------------------------------------------------------
// Answer rendering — Telegram MarkdownV2
// ---------------------------------------------------------------------------
//
// Telegram MarkdownV2 is strict: any of `_*[]()~\`>#+-=|{}.!` outside of
// matched markdown constructs must be backslash-escaped or Telegram returns
// 400 "can't parse entities". We build the message as plain text first,
// escape each free-form field, then assemble with controlled markdown.

function renderAnswerMarkdown(question, data) {
  const answer = data.answer || data.instructions || data.response || "";
  const items  = data.results || data.engrams || data.hits || [];
  const top    = Array.isArray(items) ? items.slice(0, TOP_ENGRAMS) : [];

  const lines = [];

  // Title: bold the question.
  lines.push(`*${escapeMdV2(truncate(question, 240))}*`);
  lines.push("");

  if (answer) {
    lines.push(escapeMdV2(truncate(answer, 2800)));
  }

  if (top.length > 0) {
    lines.push("");
    lines.push("__Top engrams__");
    for (const r of top) {
      const surface = String(r.surface || r.meta?.surface || "—");
      const ts      = String(r.ts || r.timestamp || "");
      const snippet = truncate(String(r.payload || r.text || ""), ENGRAM_SNIPPET_CHARS);
      // Each engram = bold surface · italic timestamp, newline, escaped snippet.
      lines.push(`*${escapeMdV2(surface)}* · _${escapeMdV2(ts)}_`);
      lines.push(escapeMdV2(snippet || "(empty)"));
      lines.push("");
    }
  } else if (!answer) {
    lines.push("_No matching engrams\\._");
  }

  return lines.join("\n");
}

// MarkdownV2 escape — per https://core.telegram.org/bots/api#markdownv2-style
// Characters that MUST be escaped outside markdown constructs:
//   _ * [ ] ( ) ~ ` > # + - = | { } . !
// We additionally escape backslash itself (must come FIRST so we don't
// double-escape the backslashes we just inserted).
function escapeMdV2(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/([_*\[\]()~`>#+\-=|{}.!])/g, "\\$1");
}

// ---------------------------------------------------------------------------
// Constant-time string compare
// ---------------------------------------------------------------------------
//
// Telegram's secret-token header is a fixed string (we set it via
// setWebhook). A naive `a === b` short-circuits on the first mismatched
// byte, leaking the secret prefix to a timing attacker. This routine
// compares every byte regardless of mismatch.
//
// We compare lengths first (length is not a secret — it's whatever the
// operator chose) and then accumulate XOR-differences across a length-equal
// buffer. Returns false if either input is empty.

function constantTimeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length === 0 || b.length === 0) return false;
  if (a.length !== b.length) return false;
  let mismatch = 0;
  for (let i = 0; i < a.length; i++) {
    mismatch |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return mismatch === 0;
}

// ---------------------------------------------------------------------------
// /telegram-setup — HTML form for the user to paste bot token + bridge URL
// ---------------------------------------------------------------------------

function renderSetupPage(url) {
  const prefilledUser = url.searchParams.get("user_id") || "";
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Eidetic for Telegram — Setup</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font: 16px/1.5 system-ui, sans-serif; max-width: 560px; margin: 4rem auto; padding: 0 1rem; color: #222; }
  h1 { font-size: 1.4rem; margin: 0 0 .5rem; }
  p  { color: #555; }
  label { display: block; margin: 1rem 0 .25rem; font-weight: 600; }
  input[type=text], input[type=password] { width: 100%; padding: .55rem .65rem; border: 1px solid #ccc; border-radius: 6px; font: inherit; }
  button { margin-top: 1.25rem; padding: .65rem 1.1rem; border: 0; border-radius: 6px; background: #229ed9; color: #fff; font: inherit; cursor: pointer; }
  small { color: #777; }
  code { background: #f1f1f4; padding: .1rem .3rem; border-radius: 4px; }
</style>
</head>
<body>
  <h1>Connect your eidetic-daemon to Telegram</h1>
  <p>Paste the bot token from <a href="https://t.me/BotFather">@BotFather</a>,
     the Cloudflare-tunnel URL of your local <code>eideticd -bridge</code>,
     the bearer token from <code>~/.eidetic/bridge-token</code>, and your
     Telegram <strong>user ID</strong>. All four stay in Cloudflare Workers
     KV; nobody else can read them.</p>
  <p><small>To find your Telegram user ID: send <code>/start</code> to
     <a href="https://t.me/userinfobot">@userinfobot</a> — it replies with
     your numeric ID.</small></p>
  <form method="POST" action="/telegram-setup">
    <label for="telegram_user_id">Telegram user ID</label>
    <input id="telegram_user_id" name="telegram_user_id" type="text"
           value="${escapeHtml(prefilledUser)}"
           placeholder="e.g. 123456789" required pattern="[0-9]{5,15}">
    <small>5–15 digit numeric ID. Must match the user invoking <code>/eidetic</code>.</small>
    <label for="bot_token">Bot token (from @BotFather)</label>
    <input id="bot_token" name="bot_token" type="password" required
           placeholder="e.g. 7891234567:AAH... (verified via getMe)">
    <small>Looks like <code>&lt;digits&gt;:&lt;mixed-case-token&gt;</code>. Used to send replies as your bot.</small>
    <label for="bridge_url">Bridge URL</label>
    <input id="bridge_url" name="bridge_url" type="text"
           placeholder="https://something.trycloudflare.com" required>
    <small>Must be HTTPS on <code>*.trycloudflare.com</code> or <code>*.cloudflare.com</code>.</small>
    <label for="token">Bearer token (eidetic-daemon)</label>
    <input id="token" name="token" type="password" required>
    <small>Contents of <code>~/.eidetic/bridge-token</code> on the machine running the daemon.</small>
    <button type="submit">Save</button>
  </form>
</body>
</html>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

async function handleSetupSubmit(request, env) {
  const rawBody = await request.text();
  const form = parseFormUrlEncoded(rawBody);
  const userId    = (form.telegram_user_id || "").trim();
  const botToken  = (form.bot_token        || "").trim();
  const bridgeUrl = (form.bridge_url       || "").trim();
  const token     = (form.token            || "").trim();

  if (!/^\d{5,15}$/.test(userId)) {
    return new Response(
      "Telegram user ID must be a 5–15 digit numeric ID. Ask @userinfobot for yours.",
      { status: 400 },
    );
  }
  if (!/^\d+:[A-Za-z0-9_-]{30,}$/.test(botToken)) {
    return new Response(
      "Bot token format looks wrong. It should be `<digits>:<mixed-case-token>` straight from @BotFather.",
      { status: 400 },
    );
  }
  if (!isAllowedBridgeUrl(bridgeUrl)) {
    return new Response(
      "Bridge URL must be HTTPS on *.trycloudflare.com or *.cloudflare.com. " +
      "Wider hostnames are intentionally rejected so a misconfigured install " +
      "can't be redirected at an arbitrary internet endpoint.",
      { status: 400 },
    );
  }
  if (!token || token.length < 16) {
    return new Response(
      "Bearer token looks too short — paste the full contents of ~/.eidetic/bridge-token.",
      { status: 400 },
    );
  }

  // Verify the bot token by calling getMe. This catches typos and revoked
  // tokens before we commit anything to KV. Telegram's getMe is a cheap
  // unauthenticated-from-outside endpoint (auth is the token in the URL).
  const meRes = await fetch(`${TELEGRAM_API_BASE}/bot${botToken}/getMe`).catch(() => null);
  if (!meRes || !meRes.ok) {
    const status = meRes ? meRes.status : "no-response";
    return new Response(
      `Could not verify bot token via Telegram getMe (HTTP ${status}). ` +
      `Re-check the token from @BotFather.`,
      { status: 400 },
    );
  }
  const me = await meRes.json().catch(() => ({}));
  if (!me.ok || !me.result?.is_bot) {
    return new Response(
      `Telegram getMe returned a non-bot response. Re-check the token from @BotFather.`,
      { status: 400 },
    );
  }

  await env.EIDETIC_TELEGRAM_KV.put(
    kvKey(userId),
    JSON.stringify({
      bot_token: botToken,
      bridge_url: bridgeUrl,
      token,
      configured_at: new Date().toISOString(),
    }),
  );

  const botUsername = String(me.result.username || "your bot");
  const html = `<!doctype html><meta charset="utf-8">
<title>Saved</title>
<body style="font: 16px/1.5 system-ui, sans-serif; max-width: 560px; margin: 4rem auto; padding: 0 1rem;">
<h1>Saved.</h1>
<p>Bot verified as <code>@${escapeHtml(botUsername)}</code>.</p>
<p>Next step: install the webhook so Telegram knows to forward updates here.
   Visit
   <a href="/telegram-setup/install/${escapeHtml(botToken)}">/telegram-setup/install/&lt;bot-token&gt;</a>
   once (the link above already has your token baked in).</p>
<p>Then send <code>/eidetic &lt;your question&gt;</code> to <code>@${escapeHtml(botUsername)}</code>
   in any chat. The Worker will route through your bridge URL and reply.</p>
</body>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

// Bridge URL allowlist — same posture as slack-app / discord-bot.
function isAllowedBridgeUrl(raw) {
  let u;
  try { u = new URL(raw); } catch { return false; }
  if (u.protocol !== "https:") return false;
  const host = u.hostname.toLowerCase();
  return host.endsWith(".trycloudflare.com") || host.endsWith(".cloudflare.com");
}

// ---------------------------------------------------------------------------
// /telegram-setup/install/<bot_token> — one-shot setWebhook caller
// ---------------------------------------------------------------------------
//
// Calls Telegram's setWebhook with this Worker's /telegram/webhook URL +
// WEBHOOK_SECRET. After this call, Telegram will POST every update for the
// given bot to our Worker, and echo the secret back in the
// X-Telegram-Bot-Api-Secret-Token header.
//
// We accept the bot token in the URL path rather than a form field so the
// user can run the install with a single browser GET (or curl). The token
// shows up in Cloudflare logs unless the operator strips request URLs — see
// README §Privacy for the trade-off.

async function handleInstallWebhook(botTokenFromPath, request, env) {
  const botToken = botTokenFromPath || env.ADMIN_BOT_TOKEN || "";
  if (!botToken) {
    return new Response(
      "Missing bot token. Visit /telegram-setup/install/<your-bot-token> or " +
      "set ADMIN_BOT_TOKEN on the Worker.",
      { status: 400 },
    );
  }
  if (!/^\d+:[A-Za-z0-9_-]{30,}$/.test(botToken)) {
    return new Response("Bot token format looks wrong.", { status: 400 });
  }
  if (!env.WEBHOOK_SECRET) {
    return new Response(
      "WEBHOOK_SECRET is not set on this Worker. Run " +
      "`wrangler secret put WEBHOOK_SECRET` first.",
      { status: 500 },
    );
  }

  const workerOrigin = new URL(request.url).origin;
  const webhookUrl   = `${workerOrigin}/telegram/webhook`;

  // setWebhook is documented at https://core.telegram.org/bots/api#setwebhook.
  // We pass `allowed_updates: ["message"]` to suppress everything we don't
  // handle (edited_message, channel_post, …) — this is a soft preference;
  // we already drop those on the receive side.
  const params = new URLSearchParams({
    url: webhookUrl,
    secret_token: env.WEBHOOK_SECRET,
    drop_pending_updates: "true",
    allowed_updates: JSON.stringify(["message"]),
  });
  const swRes = await fetch(`${TELEGRAM_API_BASE}/bot${botToken}/setWebhook`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: params.toString(),
  }).catch((err) => ({ ok: false, _err: err }));

  if (!swRes || !swRes.ok) {
    const status = swRes && swRes.status ? swRes.status : "no-response";
    let detail = "";
    if (swRes && typeof swRes.text === "function") {
      detail = (await swRes.text().catch(() => "")) || "";
    }
    return new Response(
      `Telegram setWebhook failed (HTTP ${status}). ${truncate(detail, 400)}`,
      { status: 502 },
    );
  }
  const swBody = await swRes.json().catch(() => ({}));
  if (!swBody.ok) {
    return new Response(
      `Telegram setWebhook returned ok=false: ${escapeHtml(String(swBody.description || "unknown"))}`,
      { status: 502 },
    );
  }

  const html = `<!doctype html><meta charset="utf-8">
<title>Webhook installed</title>
<body style="font: 16px/1.5 system-ui, sans-serif; max-width: 560px; margin: 4rem auto; padding: 0 1rem;">
<h1>Webhook installed.</h1>
<p>Telegram will now POST updates for your bot to
   <code>${escapeHtml(webhookUrl)}</code> with the secret token attached.</p>
<p>Send <code>/eidetic &lt;your question&gt;</code> to your bot to test.</p>
<p><small>If you ever rotate <code>WEBHOOK_SECRET</code> on the Worker, re-visit
   this URL to refresh Telegram's stored copy.</small></p>
</body>`;
  return new Response(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

// ---------------------------------------------------------------------------
// KV helpers
// ---------------------------------------------------------------------------

function kvKey(userId) {
  return `user:${userId}`;
}

async function loadUserConfig(env, userId) {
  const raw = await env.EIDETIC_TELEGRAM_KV.get(kvKey(userId));
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

// ---------------------------------------------------------------------------
// Generic helpers
// ---------------------------------------------------------------------------

function parseFormUrlEncoded(body) {
  const out = {};
  for (const pair of body.split("&")) {
    if (!pair) continue;
    const eq = pair.indexOf("=");
    const k = eq === -1 ? pair : pair.slice(0, eq);
    const v = eq === -1 ? "" : pair.slice(eq + 1);
    out[decodeURIComponent(k.replace(/\+/g, " "))] =
      decodeURIComponent(v.replace(/\+/g, " "));
  }
  return out;
}

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

function truncate(s, n) {
  if (!s) return "";
  return s.length > n ? `${s.slice(0, n - 1)}…` : s;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
