#!/usr/bin/env python3
"""
Nucleus Synthesizer Orchestrator
=================================
The "God Mode" entry point.

This script:
1. Reads the event stream (last 50 events)
2. Matches events to triggers
3. Spawns ephemeral agents for each matched trigger
4. Generates daily digest (if run in the morning)
5. Handles CRITICAL escalations

Run via cron: 0 8 * * * /path/to/scripts/run_orchestrator.sh

Location: scripts/orchestrator.py
"""

import os
import sys
import asyncio
from datetime import datetime
from pathlib import Path

# Add project to path
PROJECT_ROOT = Path(__file__).parent.parent
SERVER_SRC = PROJECT_ROOT / "mcp-server-nucleus" / "src"
sys.path.insert(0, str(SERVER_SRC))

from mcp_server_nucleus.runtime.factory import ContextFactory
from mcp_server_nucleus.runtime.agent import EphemeralAgent
from mcp_server_nucleus.runtime.event_stream import (
    read_events, 
    emit_event, 
    get_critical_events,
    EventSeverity,
    EventTypes
)
from mcp_server_nucleus.runtime.triggers import match_triggers, get_agents_for_event

# Configuration
BRAIN_PATH = Path(os.environ.get("NUCLEUS_BRAIN_PATH", PROJECT_ROOT / ".brain"))
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")


async def process_events(factory: ContextFactory) -> dict:
    """
    Process unhandled events from the stream.
    Returns summary of actions taken.
    """
    events = read_events(BRAIN_PATH, limit=50)
    
    summary = {
        "events_processed": 0,
        "agents_spawned": [],
        "critical_escalations": [],
        "errors": []
    }
    
    for event in events:
        # Skip already processed (check for completion event)
        event_id = event.get("event_id")
        
        # Match triggers
        matched = match_triggers(BRAIN_PATH, event)
        
        for match in matched:
            agent_name = match["agent"]
            
            # Skip if we're the synthesizer (avoid self-loops)
            if agent_name.lower() == "synthesizer" and event.get("emitter") == "orchestrator":
                continue
            
            # Create context for the agent
            context = factory.create_context_for_persona(
                session_id=f"orch-{event_id}-{agent_name}",
                persona_name=agent_name,
                intent=match.get("description", "Execute triggered task")
            )
            
            event_type = event.get('event_type') or event.get('type', 'unknown')
            print(f"🚀 Spawning {agent_name} for event: {event_type}")
            summary["agents_spawned"].append({
                "agent": agent_name,
                "event": event_type,
                "trigger": match.get("trigger_id")
            })
            
            # Note: In production, you'd actually spawn and run the agent here
            # For now, we log the action
            summary["events_processed"] += 1
    
    return summary


async def handle_critical_events() -> list:
    """
    Check for CRITICAL events that need immediate escalation.
    Returns list of critical events for founder notification.
    """
    criticals = get_critical_events(BRAIN_PATH, limit=10)
    
    escalations = []
    for event in criticals:
        escalations.append({
            "event_id": event.get("event_id"),
            "event_type": event.get("event_type"),
            "emitter": event.get("emitter"),
            "payload": event.get("payload"),
            "timestamp": event.get("timestamp")
        })
    
    return escalations


def generate_daily_digest(summary: dict, criticals: list) -> str:
    """
    Generate the daily digest per synthesizer.md protocol.
    """
    now = datetime.now()
    
    digest = f"""# Founder Digest: {now.strftime('%Y-%m-%d')}

## 🚨 Requires Decision ({len(criticals)} items)
"""
    
    if criticals:
        for c in criticals[:5]:
            digest += f"- [{c['event_type']}] {c['payload']}\n"
    else:
        digest += "_No critical items requiring your decision._\n"
    
    digest += f"""
## ✅ Auto-Approved ({summary['events_processed']} items)
"""
    
    if summary['agents_spawned']:
        for spawn in summary['agents_spawned'][:10]:
            digest += f"- {spawn['agent']} handled {spawn['event']}\n"
    else:
        digest += "_No automated actions taken._\n"
    
    digest += f"""
## 📊 Metrics
- Events processed: {summary['events_processed']}
- Agents spawned: {len(summary['agents_spawned'])}
- Critical escalations: {len(criticals)}
- Errors: {len(summary.get('errors', []))}

## 💡 Cross-Domain Insight
_Synthesizer insight would go here based on pattern analysis._

## 🔧 System Health
- Next meta-optimization: 72h
- Orchestrator status: ✅ Healthy

---
Generated by Nucleus Orchestrator at {now.isoformat()}
"""
    
    return digest


async def run_orchestrator():
    """Main orchestrator loop"""
    print("=" * 60)
    print(f"NUCLEUS ORCHESTRATOR - {datetime.now().isoformat()}")
    print("=" * 60)
    
    # Initialize factory
    factory = ContextFactory(brain_path=BRAIN_PATH)
    
    # Step 1: Process events
    print("\n📥 Processing event stream...")
    summary = await process_events(factory)
    print(f"   Processed {summary['events_processed']} events")
    print(f"   Spawned {len(summary['agents_spawned'])} agents")
    
    # Step 2: Handle criticals
    print("\n🚨 Checking for critical events...")
    criticals = await handle_critical_events()
    if criticals:
        print(f"   Found {len(criticals)} CRITICAL events!")
    else:
        print("   No critical events.")
    
    # Step 3: Generate daily digest
    print("\n📋 Generating daily digest...")
    digest = generate_daily_digest(summary, criticals)
    
    # Save digest
    digest_path = BRAIN_PATH / "artifacts" / "synthesis" / f"digest_{datetime.now().strftime('%Y%m%d')}.md"
    digest_path.parent.mkdir(parents=True, exist_ok=True)
    digest_path.write_text(digest)
    print(f"   Saved to: {digest_path}")
    
    # Step 4: Emit orchestrator completion event
    emit_event(
        brain_path=BRAIN_PATH,
        event_type=EventTypes.DAILY_DIGEST_GENERATED,
        emitter="orchestrator",
        payload={
            "digest_path": str(digest_path),
            "events_processed": summary["events_processed"],
            "agents_spawned": len(summary["agents_spawned"]),
            "critical_count": len(criticals)
        },
        severity=EventSeverity.ROUTINE
    )
    
    print("\n" + "=" * 60)
    print("ORCHESTRATOR COMPLETE")
    print("=" * 60)
    
    # Print digest preview
    print("\n📄 DIGEST PREVIEW:\n")
    print(digest[:500] + "...")
    
    return summary


if __name__ == "__main__":
    asyncio.run(run_orchestrator())
